blueprintSchema: sp-blueprint/v1
kind: StorageConfiguration
metadata:
  size: large
mdisk-configs:
  - storage-requirement : 'database'
    usage: 'Database container and active logs'
    disk-type : '1.92 TB NVME'
    disk-quantity: 9
    hot-spare: '1 (rebuild areas=1)'
    raid-type: 'Distributed RAID 6'
    raid-array-count: '1 (9 DDM)'
    usable-size: '10.38 TB'
    mdisk-group-name: 
      - 'db_grp0'
    mdisk-array-name: 
      - 'db_array0'
  - storage-requirement : 'storage-pool'
    usage: 'Storage pool, archive log, and database backups'
    disk-type : '8 TB NL-SAS'
    disk-quantity: 184
    hot-spare: '8 (rebuild areas=2 per array)'
    raid-type: 'Distributed RAID 6'
    raid-array-count: '4 (46 DDM)'
    usable-size: '265.18 TB'
    mdisk-group-name: 
      - 'stgpool_grp0'
    mdisk-array-name: 
      - 'stgpool_array0'
      - 'stgpool_array1'
      - 'stgpool_array2'
      - 'stgpool_array3'

volume-configs:
  - storage-requirement : 'database'
    volumes:
      - volume-name: 
          - 'db_00'
          - 'db_01'
          - 'db_02'
          - 'db_03'
          - 'db_04'
          - 'db_05'
          - 'db_06'
          - 'db_07'
          - 'db_08'
          - 'db_09'
          - 'db_10'
          - 'db_11'
        usage: 'Database'
        quantity: 12
        mdisk-group-name: 'db_grp0'
        size-per-volume: '837.89 GB'
        mount-point:
          - '/tsminst1/TSMdbspace00'
          - '/tsminst1/TSMdbspace01'
          - '/tsminst1/TSMdbspace02'
          - '/tsminst1/TSMdbspace03'
          - '/tsminst1/TSMdbspace04'
          - '/tsminst1/TSMdbspace05'
          - '/tsminst1/TSMdbspace06'
          - '/tsminst1/TSMdbspace07'
          - '/tsminst1/TSMdbspace08'
          - '/tsminst1/TSMdbspace09'
          - '/tsminst1/TSMdbspace10'
          - '/tsminst1/TSMdbspace11'
      - volume-name: 
          - 'alog'
        usage: 'Active log'
        quantity: 1
        mdisk-group-name: 'db_grp0'
        size-per-volume: '550 GB'
        mount-point:
          - '/tsminst1/TSMalog'
      - volume-name: 
          - 'archlog_00'
        usage: 'Archive log'
        quantity: 1
        mdisk-group-name: 'stgpool_grp0'
        size-per-volume: '4 TB'
        mount-point:
          - '/tsminst1/TSMarchlog'
      - volume-name: 
          - 'backup_00'
          - 'backup_01'
          - 'backup_02'
        usage: 'Database backup'
        quantity: 2
        mdisk-group-name: 'stgpool_grp0'
        size-per-volume: '18 TB'
        mount-point:
          - '/tsminst1/TSMbkup00'
          - '/tsminst1/TSMbkup01'
          - '/tsminst1/TSMbkup02'
  - storage-requirement : 'storage-pool'
    volumes:
      - volume-name: 
          - 'filepool_00'
          - 'filepool_01'
          - 'filepool_02'
          - 'filepool_03'
          - 'filepool_04'
          - 'filepool_05'
          - 'filepool_06'
          - 'filepool_07'
          - 'filepool_08'
          - 'filepool_09'
          - 'filepool_10'
          - 'filepool_11'
          - 'filepool_12'
          - 'filepool_13'
          - 'filepool_14'
          - 'filepool_15'
          - 'filepool_16'
          - 'filepool_17'
          - 'filepool_18'
          - 'filepool_19'
          - 'filepool_20'
          - 'filepool_21'
          - 'filepool_22'
          - 'filepool_23'
          - 'filepool_24'
          - 'filepool_25'
          - 'filepool_26'
          - 'filepool_27'
          - 'filepool_28'
          - 'filepool_29'
          - 'filepool_30'
          - 'filepool_31'
        usage: 'IBM Storage Protect file systems for a directory-container storage pool'
        quantity: 32
        mdisk-group-name: 'stgpool_grp0'
        size-per-volume: '31.33 TB'
        mount-point:
          - '/tsminst1/TSMfile00'
          - '/tsminst1/TSMfile01'
          - '/tsminst1/TSMfile02'
          - '/tsminst1/TSMfile03'
          - '/tsminst1/TSMfile04'
          - '/tsminst1/TSMfile05'
          - '/tsminst1/TSMfile06'
          - '/tsminst1/TSMfile07'
          - '/tsminst1/TSMfile08'
          - '/tsminst1/TSMfile09'
          - '/tsminst1/TSMfile10'
          - '/tsminst1/TSMfile11'
          - '/tsminst1/TSMfile12'
          - '/tsminst1/TSMfile13'
          - '/tsminst1/TSMfile14'
          - '/tsminst1/TSMfile15'
          - '/tsminst1/TSMfile16'
          - '/tsminst1/TSMfile17'
          - '/tsminst1/TSMfile18'
          - '/tsminst1/TSMfile19'
          - '/tsminst1/TSMfile20'
          - '/tsminst1/TSMfile21'
          - '/tsminst1/TSMfile22'
          - '/tsminst1/TSMfile23'
          - '/tsminst1/TSMfile24'
          - '/tsminst1/TSMfile25'
          - '/tsminst1/TSMfile26'
          - '/tsminst1/TSMfile27'
          - '/tsminst1/TSMfile28'
          - '/tsminst1/TSMfile29'
          - '/tsminst1/TSMfile30'
          - '/tsminst1/TSMfile31'
